name: Autograding
description: "Autograding for GitHub Classroom"
author: "@github"
inputs:
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}
  points:
    description: >
      The number of points scored for this assignment. Must be an integer.
    required: false
  available-points:
    description: >
      The total number of points available for this assignment. Must be an integer.
    required: false
runs:
  using: "node16"
  main: "./dist/index.js"
